"""add_crop_analysis_table

Revision ID: dc4eb77ebf59
Revises: 9e4ab67d4a2e
Create Date: 2026-08-20 20:43:47.119268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4eb77ebf59'
down_revision: Union[str, None] = '9e4ab67d4a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_analyses',
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('image_key', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('analysis_type', sa.String(length=100), nullable=False),
    sa.Column('model_status', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('image_valid', sa.Boolean(), nullable=True),
    sa.Column('image_format', sa.String(length=20), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('quality_notes', sa.JSON(), nullable=True),
    sa.Column('vegetation_proxy', sa.JSON(), nullable=True),
    sa.Column('observations', sa.JSON(), nullable=True),
    sa.Column('raw_metrics', sa.JSON(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], name=op.f('fk_crop_analyses_farm_id_farms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop_analyses'))
    )
    with op.batch_alter_table('crop_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_crop_analyses_farm_created', ['farm_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crop_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_crop_analyses_farm_created')

    op.drop_table('crop_analyses')
    # ### end Alembic commands ###
